"""users remove name, age column

Revision ID: 892c53e029de
Revises: 5d64c6308c22
Create Date: 2023-05-07 14:01:52.373921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '892c53e029de'
down_revision = '5d64c6308c22'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
