"""delete name, age column

Revision ID: d685f48ad1f5
Revises: 0752c03cd92f
Create Date: 2023-05-08 21:07:47.584207

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd685f48ad1f5'
down_revision = '0752c03cd92f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # op.create_table('users',
    # sa.Column('user_id', sa.Integer(), autoincrement=True, nullable=False),
    # sa.Column('email', sa.Text(), nullable=False),
    # sa.Column('password', sa.Text(), nullable=False),
    # sa.PrimaryKeyConstraint('user_id')
    op.drop_table('users')
    # )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
